#!/bin/sh

PORTS="eth0 wlan0"

if [ "$1" == "open" ]
then
  echo "Open"
  #Drop all rules
  iptables -F
  iptables -X
  iptables -P INPUT ACCEPT
  iptables -P OUTPUT ACCEPT
  iptables -P FORWARD ACCEPT
else
  #Drop all rules
  iptables -F
  iptables -X
  
  #Close evrything
  iptables -P INPUT DROP
  iptables -P OUTPUT DROP
  iptables -P FORWARD DROP
  
  #Allow all connections on lo
  iptables -A INPUT -i lo  -j ACCEPT
  iptables -A OUTPUT -o lo -j ACCEPT
  
  for PORT in $PORTS
  do
    #Allow incoming ping
    iptables -A INPUT  -p icmp -i $PORT --icmp-type 8 -s 0/0 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
    iptables -A OUTPUT -p icmp -o $PORT --icmp-type 0 -d 0/0 -m state --state ESTABLISHED,RELATED     -j ACCEPT

    #Alow outgoing http connections (port 80)
    iptables -A INPUT  -p tcp -i $PORT --sport 80 -m state --state ESTABLISHED     -j ACCEPT
    iptables -A OUTPUT -p tcp -o $PORT --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT

    #Alow outgoing https connections (port 443)
    iptables -A INPUT  -p tcp -i $PORT --sport 443 -m state --state ESTABLISHED     -j ACCEPT
    iptables -A OUTPUT -p tcp -o $PORT --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT

    #Allow DNS (port 53)
    iptables -A OUTPUT -p udp -o $PORT --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
    iptables -A INPUT  -p udp -i $PORT --sport 53 -m state --state ESTABLISHED     -j ACCEPT
    iptables -A OUTPUT -p tcp -o $PORT --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
    iptables -A INPUT  -p tcp -i $PORT --sport 53 -m state --state ESTABLISHED     -j ACCEPT
    iptables -I INPUT -i $PORT -p udp --dport 67:68 --sport 67:68 -j ACCEPT
  done

  #Alow incoming labview sessions  (port 5001)
  iptables -A INPUT  -p tcp -i eth0 --dport 5001 -m state --state NEW,ESTABLISHED -j ACCEPT
  iptables -A OUTPUT -p tcp -o eth0 --sport 5001 -m state --state ESTABLISHED     -j ACCEPT

  #Alow incoming telnet sessions (port 23)
  #iptables -A INPUT  -p tcp -i eth0 --dport 23 -m state --state NEW,ESTABLISHED -j ACCEPT
  #iptables -A OUTPUT -p tcp -o eth0 --sport 23 -m state --state ESTABLISHED     -j ACCEPT
fi
  
